AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template for the security groups: FargateContainer - SecurityGroups

Parameters:

  EnvironmentName:
    Description: An Environment Name to name the resources
    Type: String
    # Default: dxhub

  ServiceName:
    Description: The Service name
    Type: String
    # Default: contactsvc

Resources:

  # A security group for the containers we will run in Fargate.

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-${ServiceName}-sg
      GroupDescription: !Sub Access to the ${ServiceName} containers
      VpcId: !ImportValue VpcId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-sg

  ServiceSecurityGroupIngressFromFargate:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from other containers in the same security group
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ServiceSecurityGroup

  ServiceIngressRule1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from the PublicLoadBalancerSG
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: tcp
      FromPort: 8081 # Needs changing
      ToPort: 8081 # Needs changing
      SourceSecurityGroupId: !ImportValue PublicALBSG

Outputs:

  ServiceSecurityGroup:
    Description: A security group for Service
    Value: !Ref ServiceSecurityGroup
    Export:
      Name: !Sub ${ServiceName}-sg # sample output - contactsvc-sg
