AWSTemplateFormatVersion: 2010-09-09
Description: A template for the ALB

Parameters:

  EnvironmentName:
    Description: The Environment Name to name the resources
    Type: String

  ServiceName:
    Description: The Service Name
    Type: String

  Path:
    Type: String
    Default: "*"
    Description: A path on the public load balancer that this service
                 should be connected to. Use * to send all load balancer
                 traffic to this service.

Resources:

  # 1. Target Groups

  ServiceTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /AWS.ALB/healthcheck
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Sub ${EnvironmentName}-${ServiceName}-1
      Port: 10542
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue VpcId

  ServiceTargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /AWS.ALB/healthcheck
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Sub ${EnvironmentName}-${ServiceName}-2
      Port: 10542
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue VpcId

  # 1. Load Balancers

  ServiceLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-${ServiceName}
      Scheme: internal
      SecurityGroups: [!ImportValue ServiceSecurityGroup]
      Subnets:
        - !ImportValue PrivateSubnet1a
        - !ImportValue PrivateSubnet1b
        - !ImportValue PrivateSubnet1c
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} ServiceLoadBalancer

# listeners

  ServiceProdListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions: # Required
        - TargetGroupArn: !Ref ServiceTargetGroup1
          Type: forward
      LoadBalancerArn: !Ref ServiceLoadBalancer # Required
      Port: 443
      Protocol: HTTPS

  ServiceTestListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions: # Required
        - TargetGroupArn: !Ref ServiceTargetGroup2
          Type: forward
      LoadBalancerArn: !Ref ServiceLoadBalancer # Required
      Port: 8443
      Protocol: HTTPS

  # 5. Load Balancer Listener Rule

  # graphql listener rules

  ServiceProdListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions: # Required
        - TargetGroupArn: !Ref ServiceTargetGroup1
          Type: forward
      Conditions: # Required
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn: !Ref ServiceProdListener # Required
      Priority: 1 # Required

  ServiceTestListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions: # Required
        - TargetGroupArn: !Ref ServiceTargetGroup2
          Type: forward
      Conditions: # Required
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn: !Ref ServiceTestListener # Required
      Priority: 1 # Required

Outputs:

  ExternalUrl:
    Description: The url of the external load balancer
    Value: !Join ['', ['http://', !GetAtt 'PublicLoadBalancer.DNSName']]
    Export:
      Name: ExternalUrl

  PublicLoadBalancerArn:
    Description: The export arn for the Public LoadBalancer
    Value: !Ref PublicLoadBalancer
    Export:
      Name: PublicLoadBalancerArn
