AWSTemplateFormatVersion: 2010-09-09
Description: A template for the ALB

Parameters:

  EnvironmentName:
    Description: The Environment Name to name the resources
    Type: String

  Path:
    Type: String
    Default: "*"
    Description: A path on the public load balancer that this service
                 should be connected to. Use * to send all load balancer
                 traffic to this service.

Resources:

  # 1. Target Groups

  ProductSvcTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /AWS.ALB/healthcheck
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Sub ${EnvironmentName}-${ServiceName2}-1
      Port: 10542
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName2}-1
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue VpcId

  ProductSvcTargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /AWS.ALB/healthcheck
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Sub ${EnvironmentName}-${ServiceName2}-2
      Port: 10542
      Protocol: HTTP
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName2}-2
      TargetType: ip
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue VpcId



  # 1. Load Balancers

  ProductSvcLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-productsvc
      Scheme: internal
      SecurityGroups: [!ImportValue ProductSvcSecurityGroup]
      Subnets:
        - !ImportValue PrivateSubnet1a
        - !ImportValue PrivateSubnet1b
        - !ImportValue PrivateSubnet1c
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} ProductSvcLoadBalancer

# listeners

  ProductSvcProdListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions: # Required
        - TargetGroupArn: !Ref ProductSvcTargetGroup1
          Type: forward
      LoadBalancerArn: !Ref ProductSvcLoadBalancer # Required
      Port: 443
      Protocol: HTTPS

  ProductSvcTestListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions: # Required
        - TargetGroupArn: !Ref ProductSvcTargetGroup2
          Type: forward
      LoadBalancerArn: !Ref ProductSvcLoadBalancer # Required
      Port: 8443
      Protocol: HTTPS

  # 5. Load Balancer Listener Rule

  # graphql listener rules

  ProjectSvcProdListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions: # Required
        - TargetGroupArn: !Ref ProjectSvcTargetGroup1
          Type: forward
      Conditions: # Required
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn: !Ref ProjectSvcProdListener # Required
      Priority: 1 # Required

  ProjectSvcTestListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions: # Required
        - TargetGroupArn: !Ref ProjectSvcTargetGroup2
          Type: forward
      Conditions: # Required
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn: !Ref ProjectSvcTestListener # Required
      Priority: 1 # Required

Outputs:

  ExternalUrl:
    Description: The url of the external load balancer
    Value: !Join ['', ['http://', !GetAtt 'PublicLoadBalancer.DNSName']]
    Export:
      Name: ExternalUrl

  PublicLoadBalancerArn:
    Description: The export arn for the Public LoadBalancer
    Value: !Ref PublicLoadBalancer
    Export:
      Name: PublicLoadBalancerArn
