# S3 URL for root - https://trox-cf-templates.s3.eu-central-1.amazonaws.com/test/alb/root.yaml

AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: dxhub

  ServiceName:
    Description: The Environment Name to name the resources
    Type: String
    Default: neocrm-api

  Certificate:
    Description: The Certificate for the listeners
    Type: String
    Default: arn:aws:acm:eu-central-1:115379056088:certificate/b7cc923c-7daa-4b4d-a69f-f550f386d872

  VpcId:
    Description: Dxhub VpcId
    Type: String
    Default: vpc-090e086f59b874011

  PublicSubnet1a:
    Description: Dxhub PublicSubnet1a
    Type: String
    Default: subnet-04ef6dbeac6590347

  PublicSubnet1b:
    Description: Dxhub PublicSubnet1b
    Type: String
    Default: subnet-0d6515159c1192fc0

  PublicSubnet1c:
    Description: Dxhub PublicSubnet1c
    Type: String
    Default: subnet-098a6dc7ffbd55c5e

  # PrivateSubnet1a:
  #   Description: Dxhub PrivateSubnet1a
  #   Type: String
  #   Default: subnet-0250df016f025d304

  # PrivateSubnet1b:
  #   Description: Dxhub PrivateSubnet1b
  #   Type: String
  #   Default: subnet-09f41e2ac8f83f639

  # PrivateSubnet1c:
  #   Description: Dxhub PrivateSubnet1b
  #   Type: String
  #   Default: subnet-07260c658f4c2a3eb

  AlbSg:
    Description: Dxhub PublicSubnet1c
    Type: String
    Default: sg-088007583ceeaf250

Resources:

  nestedALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceName
        Certificate: !Ref Certificate
        VpcId: !Ref VpcId
        PublicSubnet1a: !Ref PublicSubnet1a
        PublicSubnet1b: !Ref PublicSubnet1b
        PublicSubnet1c: !Ref PublicSubnet1c
        # PrivateSubnet1a: !Ref PrivateSubnet1a
        # PrivateSubnet1b: !Ref PrivateSubnet1b
        # PrivateSubnet1c: !Ref PrivateSubnet1c
        AlbSg: !Ref AlbSg
      TemplateURL: https://dxhub-cf-templates.s3.eu-central-1.amazonaws.com/alb/ecs-services/alb-internet-facing/alb.yaml

  