AWSTemplateFormatVersion: 2010-09-09
Description: AN ECS Cluster Template creating ECS Task Definition, ECS Service and CloudWatch groups

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: dxhub

  ServiceName:
    Description: The name of first service
    Type: String
    Default: neocrm-api

  ServiceECRRepository:
    Description: The Service ECR Repository
    Type: String
    Default: neocrm-api

  ServiceCluster:
    Description: The ECS Cluster for the service
    Type: String
    Default: neocrm-svc

  DynamodbInstance:
      Description: DbHost from Parameter Store for the container
      Type: String
      Default: arn:aws:ssm:eu-central-1:115379056088:parameter/dxhub/DATABASE_AWS_DYNAMODB_INSTANCE_TABLE

  HoneyBagerkey:
      Description: DbHost from Parameter Store for the container
      Type: String
      Default: arn:aws:ssm:eu-central-1:115379056088:parameter/dxhub/DATABASE_AWS_DYNAMODB_INSTANCE_TABLE

  JRapi:
      Description: DbHost from Parameter Store for the container
      Type: String
      Default: arn:aws:ssm:eu-central-1:115379056088:parameter/dxhub/DATABASE_AWS_DYNAMODB_INSTANCE_TABLE

  ECSTaskExecutionRoleArn:
      Description: ECS Task Execution Role
      Type: String
      Default: arn:aws:ssm:eu-central-1:115379056088:parameter/dxhub/DATABASE_AWS_DYNAMODB_INSTANCE_TABLE

Resources:

  nestedECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceName
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/service/nested-ecs.yaml

  nestedDeployment:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceName
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/service/nested-deployment.yaml
