AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template for the security groups: LoadBalacer and FargateContainer -SecurityGroups

Parameters:

  EnvironmentName:
    Description: An Environment Name to name the resources
    Type: String

  ServiceName:
    Description: The Service name
    Type: String

  PublicLoadBalancerSG:
    Description: The Service name
    Type: String
    Default: sg-0d1749afcec14e6b2

Resources:

  # A security group for the containers we will run in Fargate.
  # Two rules, allowing network traffic from a public facing load
  # balancer and from other members of the security group.
  #
  # If you want to make direct requests to a container using its
  # public IP address you'll need to add a security group rule
  # to allow traffic from all IP addresses.

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName} ServiceSecurityGroup
      GroupDescription: !Sub Access to the ${ServiceName} containers
      VpcId: !ImportValue VpcId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-sg

  ServiceSecurityGroupIngressFromPublicALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from the public ALB
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref PublicLoadBalancerSG

  ServiceCustomPort:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from other containers in the same security group
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: tcp
      FromPort: 8081
      ToPort: 8081
      SourceSecurityGroupId: !Ref ServiceSecurityGroup

  # Load balancers for getting traffic to containers.
  # This sample template creates one load balancer:
  #
  # - One public load balancer, hosted in public subnets that is accessible
  #   to the public, and is intended to route traffic to one or more public
  #   facing services.

  # A public facing load balancer, this is used for accepting traffic from the public
  # internet and directing it to public facing microservices


Outputs:

  ServiceSecurityGroup:
    Description: A security group used to allow Fargate containers to receive traffic
    Value: !Ref ServiceSecurityGroup
    Export:
      Name: ServiceSecurityGroup

