AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    # Default: dxhub

  GithubTiggerFunctionName:
    Description: The name lambda function for github tigger
    Type: String
    # Default: github-trigger-codepipeline

  CodedeployFunctionName:
    Description: The name of first service code deploy lifecycle
    Type: String
    # Default: codedeploy-lifecycle
    
Resources:

# 1. ECR Repositories

  GithubTiggerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${EnvironmentName}-${GithubTiggerFunctionName}

  CodeDeployECRRepository2:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${EnvironmentName}-${CodedeployFunctionName}

# 2. Lambda Functions

  GithubTiggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${EnvironmentName}-${GithubTiggerFunctionName}
      PackageType: Image
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-${GithubTiggerECRRepository}
      Role: !ImportValue GithubTriggerCodePipelineArn
      Timeout: 30
      MemorySize: 256

  CodeDeployLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${EnvironmentName}-${CodedeployFunctionName}
      PackageType: Image
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-${CodedeployFunctionName}
      Role: !ImportValue GithubTriggerCodePipelineArn
      Timeout: 30
      MemorySize: 256

Outputs:
  GithubTiggerFunction:
    Description: Export value for the cluster lambda function for github trigger
    Value: !GetAtt GithubTiggerLambdaFunction.Arn
    Export:
      Name: GithubTiggerLambdaFunctionArn

  CodeDeployLambdaFunction:
    Description: Export value for the cluster lambda function for codelifecycle
    Value: !GetAtt CodeDeployLambdaFunction.Arn
    Export:
      Name: CodeDeployLambdaFunctionArn

