# S3 URL for root - https://trox-backend-cf.s3.eu-central-1.amazonaws.com/Test/iam/root.yaml

AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: dxhub

  # DBName:
  #   Description: The Database Name 
  #   Type: String
  #   Default: dxhub-postgres

Resources:

  nestedRDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        # DBName: !Ref DBName
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/rds/rds.yaml
