AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: 'dxhub'

Resources:

  nestedNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/nested-network.yaml
  nestedSecurity:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - nestedNetwork
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/nested-security.yaml
