AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template for the security groups: FargateContainer - SecurityGroups

Parameters:

  EnvironmentName:
    Description: An Environment Name to name the resources
    Type: String
    # Default: dxhub

  ServiceName:
    Description: The Service name
    Type: String
    # Default: contactsvc

  VpcId:
    Description: Dxhub VpcId
    Type: String
    # Default: vpc-090e086f59b874011

  # PublicALBSG:
  #   Description: dxhub public alb sg
  #   Type: String
  #   # Default: sg-003c7e67c72bf48e4

  InternalAlbSG:
    Description: dxhub internal alb sg
    Type: String
    # Default: sg-07c9788301fb28980

  # CodeDeploySG:
  #   Description: dxhub code-deploy alb sg
  #   Type: String
  #   # Default: sg-0b749210a35085de6

Resources:

  # A security group for the containers we will run in Fargate.

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-${ServiceName}-sg
      GroupDescription: !Sub Access to the ${ServiceName} containers
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-${ServiceName}-sg

  ServiceSecurityGroupIngressFromFargate:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from other containers in the same security group
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ServiceSecurityGroup

  # # Add this security group - ingress rule if your service is publicly accessible - ( externally accessible )

  # ServiceIngressRule1:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   Properties:
  #     Description: Ingress from the PublicLoadBalancerSG
  #     GroupId: !Ref ServiceSecurityGroup
  #     IpProtocol: tcp
  #     FromPort: 8081
  #     ToPort: 8081
  #     SourceSecurityGroupId: !Ref PublicALBSG

  # Add this security group - ingress rule if your service is not publicly accessible - ( internally accessible in vpc )

  ServiceIngressRule1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from the InternalAlbSG
      GroupId: !Ref ServiceSecurityGroup
      IpProtocol: tcp
      FromPort: 8101
      ToPort: 8101
      SourceSecurityGroupId: !Ref InternalAlbSG

  # # Add this security group - ingress rule if your service will use the CodeDeploy LifeCycle Lambda Function

  # ServiceIngressRule2:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   Properties:
  #     Description: Ingress from the CodeDeployLifeCyleSG
  #     GroupId: !Ref ServiceSecurityGroup
  #     IpProtocol: tcp
  #     FromPort: 8081
  #     ToPort: 8081
  #     SourceSecurityGroupId: !Ref CodeDeploySG

Outputs:

#####
  # The export section creates a concatenation on the export name using ServiceName that you can import using !ImportValue function then with the exact format of the concatenated string
  # i.e !ImportValue contactsvc-sg
#####

  ServiceSecurityGroup:
    Description: A security group for Service
    Value: !Ref ServiceSecurityGroup
    Export:
      Name: !Sub ${ServiceName}-sg

