AWSTemplateFormatVersion: 2010-09-09
Description: AN ECS Cluster Template creating ECS Task Definition, ECS Service and CloudWatch groups

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: dxhub

  ServiceName:
    Description: The name of first service
    Type: String
    Default: contactsvc

  HoneyBagerkey:
    Description: DbHost from Parameter Store for the container
    Type: String
    Default: arn:aws:ssm:eu-west-2:012615398682:parameter/dxhub/HONEYBADGER_API_KEY

  DBHost:
    Description: DbHost from Parameter Store for the container
    Type: String
    Default: arn:aws:ssm:eu-west-2:012615398682:parameter/dxhub/POSTGRES_HOST

  DBName:
    Description: DbHost from Parameter Store for the container
    Type: String
    Default: arn:aws:ssm:eu-west-2:012615398682:parameter/dxhub/POSTGRES_DATABASE

  DBUsername:
    Description: Db username from Parameter Store for the container
    Type: String
    Default: arn:aws:ssm:eu-west-2:012615398682:parameter/dxhub/POSTGRES_USERNAME

  # DBPassword:
  #   Description: Db password from Parameter Store for the container
  #   Type: String
  #   Default: arn:aws:ssm:eu-west-2:012615398682:parameter/dxhub/contactsvc/POSTGRES_PASSWORD

Resources:

  nestedECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceName
        HoneyBagerkey: !Ref HoneyBagerkey
        DBHost: !Ref DBHost
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        # DBPassword: !Ref DBPassword
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/contactsvc/ecs-service/ecs.yaml
