AWSTemplateFormatVersion: 2010-09-09
Description: AN ECS Cluster Template creating ECS Task Definition, ECS Service and CloudWatch groups

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: dxhub

  GithubTiggerFunctionName:
    Description: The name lambda function for github tigger
    Type: String
    Default: github-trigger-codepipeline

  CodedeployFunctionName:
    Description: The name of first service code deploy lifecycle
    Type: String
    Default: codedeploy-lifecycle

Resources:

  nestedECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        GithubTiggerFunctionName: !Ref GithubTiggerFunctionName
        CodedeployFunctionName: !Ref CodedeployFunctionName
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/dxhub-infra/ecs-service/ecs.yaml