# S3 URL for root - https://trox-cf-templates.s3.eu-central-1.amazonaws.com/test/alb/root.yaml

AWSTemplateFormatVersion: 2010-09-09

Parameters:

  EnvironmentName:
    Description: The Stack Name for naming the resources
    Type: String
    Default: dxhub

  ServiceName:
    Description: The Environment Name to name the resources
    Type: String
    Default: neocrm-api

  Certificate:
    Description: The Certificate for the listeners
    Type: String
    Default: arn:aws:acm:eu-central-1:012615398682:certificate/b697e4c5-8dd6-4d90-b6e4-0e729673584d

Resources:

  nestedALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceName
        Certificate: !Ref Certificate
      TemplateURL: https://dxhub-infra-templates.s3.eu-central-1.amazonaws.com/alb/internet-facing/nested-alb.yaml

  